#端口号
server:
  port: 8088
#数据库的配置信息
spring:
  datasource: #数据源配置
    url: jdbc:mysql://rm-hp3qgn64g7i3s4yujco.mysql.huhehaote.rds.aliyuncs.com:3306/app?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-active: 200 #最大连接池数量
      max-wait: 1200 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: false #PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      validation-query: SELECT 1
      validation-query-timeout: 3
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      time-between-eviction-runs-millis: 60000 #test-while-idle的判断依据
      min-evictable-idle-time-millis: 30000 #连接保持空闲而不被驱逐的最小时间
      async-close-connection-enable: true
      filters: stat,wall,slf4j
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql

    redis:
      host: 39.104.60.156
      port: 6379
      password:
      database: 10
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1
mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  #mybatis
  #Mapper路径
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.demo.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #数据库字段与数据对象字段的映射策略
    map-underscore-to-camel-case: true
    cache-enabled: false

  global-config:
    db-config:
      #      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      #      id-type: id_worker
      #      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy: not_empty
      #      #驼峰下划线转换
      #      column-underline: true
      #      #数据库大写下划线转换
      #      #capital-mode: true
      #      #逻辑删除配置
      #      logic-delete-value: Y
      #      logic-not-delete-value: N
      #数据库类型。支持主流的数据库
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
      #    sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
